name: parking_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  injector: ^3.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.1.0
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/car.png
    - assets/images/placa-estacionamento-estacionar.png
    - assets/images/placa-estacionamento-proibido.png

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700
